config/routes.rb
Rails.application.routes.draw do
  resources :suggestions
  match 'suggestions/:id/add_to_watchlist' => 'suggestions#add_to_watchlist', as: :suggestion_add_watchlist, via: [:get, :post]
  match 'suggestions/:id/remove_from_watchlist' => 'suggestions#remove_from_watchlist', as: :suggestion_remove_watchlist, via: [:get, :post]
  resources :itineraries # à retravailler pour n'avoir que les routes nécessaires
  resources :language_user_joints
  devise_for :users
  root to: 'pages#home'
  mount ForestLiana::Engine => '/forest'
  get '/profile', to: 'pages#profile'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_modal_watchlist_disconnected.html.erb
<div class="modal fade" id="watchlist_disconnected" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h5 class="modal-title" id="exampleModalLabel">You need to have an account!</h5>
      </div>
      <!-- <div class="modal-body">
        <p>
          Log in or create an account!
        </p>
      </div> -->
      <div class="modal-footer">
        <%= link_to "Sign in", new_user_session_path, class: "btn btn-warning" %>
        <%= link_to "Sign up", new_user_registration_path, class: "btn btn-success" %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo_SC_2.svg", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <% if user_signed_in? %>
      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "user.svg", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to profile_url do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
<!--             <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li> -->
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item navbar-xs-menu hidden-md hidden-lg">
    <% if user_signed_in? %>
      <div class="dropdown">
        <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><%= link_to "New itinerary", new_itinerary_url  %></li>
          <li><%= link_to "Dashboard", profile_url %></li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
            <% end %>
          </li>
        </ul>
      </div>
    <% else %>
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

</div>

app/views/shared/_suggestion_card.html.erb
  <div class="col-xs-12 col-sm-3"  >
  <%#= render 'suggestions/watchlist_button', suggestion: suggestion %>
    <div class="card-suggestion">
    <!-- Need to rework layout and css classes -->
      <div id="watchlist-suggestion-<%= suggestion.id %>">
        <%= render 'shared/watchlist_btn', suggestion: suggestion%>
      </div>
      <%= link_to suggestion_path(suggestion), :method => :put, :target => '_blank' do %>
      <span class="name"><%= suggestion.inspiration.name %> </span>
      <span class="duration"><%= suggestion.inspiration.duration %> min</span>
      <br><br>
      <span class="source">From <%= suggestion.inspiration.source %></span>
    </div>
  </div>
<% end %>

app/views/shared/_watchlist_btn.html.erb
<% if user_signed_in? %>
  <% if suggestion.watchlisted %>
    <%= link_to suggestion_remove_watchlist_path(suggestion), remote: true do  %>
      <i class="fas fa-check green-remove-watchlist "></i>
    <% end %>
  <% else %>
    <%= link_to suggestion_add_watchlist_path(suggestion), remote: true do  %>
      <i class="fas fa-plus yellow-add-watchlist"></i>
    <% end %>
  <% end %>
<% else %>
  <%#= link_to new_user_session_path do %>
  <%= link_to "#watchlist_disconnected", "data-toggle" => "modal" do %>
    <i class="fas fa-check green-remove-watchlist "></i>
  <% end %>
<% end %>