config/routes.rb
Rails.application.routes.draw do
  resources :suggestions
  match 'suggestions/:id/add_to_watchlist' => 'suggestions#add_to_watchlist', as: :suggestion_add_watchlist, via: [:get, :post]
  match 'suggestions/:id/remove_from_watchlist' => 'suggestions#remove_from_watchlist', as: :suggestion_remove_watchlist, via: [:get, :post]
  resources :itineraries # à retravailler pour n'avoir que les routes nécessaires
  resources :language_user_joints
  devise_for :users
  root to: 'pages#home'
  mount ForestLiana::Engine => '/forest'
  get '/profile', to: 'pages#profile'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/views/pages/home.html.erb
<div class="background-image">
  <div class="container ">
    <div class="home-content">
      <div class="home-title">
        <h1>Sick of losing time during your <br>commute?</h1>
      </div>
      <div class="row home-tips">
        <!-- <div class=""> -->
          <div class="card-home home-commute col-xs-12 col-md-4 ">
            <div class="icon-home commute">
              <%= image_tag "train_style2.svg" %>
            </div>
            <div class="tip-home commute">
              <h3>Spending time in <span class="emphasis">commute everyday</span>?</h3>
            </div>
          </div>
          <div class="card-home home-time col-xs-12 col-md-4 ">
            <div class="icon-home value">
              <%= image_tag "value.svg" %>
            </div>
            <div class="tip-home value">
              <h3>Get <span class="emphasis">quality content</span>...</h3>
            </div>
          </div>
          <div class="card-home home-time col-xs-12 col-md-4 ">
            <div class="icon-home time">
              <%= image_tag "time.svg" %>
            </div>
            <div class="tip-home time">
              <h3>...for just <span class="emphasis">the right time span</span></h3>
            </div>
          </div>
        <!-- </div> -->
      </div>
      <%= link_to "Join Smart-commute", new_itinerary_path, class:'btn btn-warning home-btn' %>
    </div>
  </div>
</div>

app/views/pages/profile.html.erb
<div class="container">
  <h1 class="title-center"><span class="emphasis-title-green">Your Profile</span></h1>
  <h2>Your preferences</h2>


    <%= simple_form_for @languageuserjoint do |f| %>
      <%= f.input :language_id, as: :check_boxes, collection: [[ 'English',Language.first.id], ['French', Language.second.id]] %>
      <%= f.hidden_field :user_id, value: current_user.id %>
    <% end %>


  <h2><span class="emphasis-subtitle-yellow">Watchlist</span> (<%= @watchlist.count%>)</h2>
  <div class="row">
    <% @watchlist.each do |suggestion| %>
      <%= render 'shared/suggestion_card', suggestion: suggestion %>
    <% end %>
  </div>

  <h2><span class="emphasis-subtitle-red">Seen</span> (<%= @seen_suggestions.count%>)</h2>
  <div class="row">
    <% @seen_suggestions.each do |suggestion| %>
      <%= render 'shared/suggestion_card', suggestion: suggestion %>
    <% end %>
  </div>

</div>